export const ROLES = {
  USER: 'user',
  ADMIN: 'admin'
}

export const PERMISSIONS = {
  'user': [
    'companies:create',
    'companies:read',
    'companies:update',
    'companies:delete',
    'applications:create',
    'applications:read',
    'applications:update',
    'applications:delete',
    'contacts:create',
    'contacts:read',
    'contacts:update',
    'contacts:delete',
    'interviews:create',
    'interviews:read',
    'interviews:update',
    'interviews:delete',
    'notes:create',
    'notes:read',
    'notes:update',
    'notes:delete',
  ],
  'admin': [
    'companies:create',
    'companies:read',
    'companies:update',
    'companies:delete',
    'applications:create',
    'applications:read',
    'applications:update',
    'applications:delete',
    'contacts:create',
    'contacts:read',
    'contacts:update',
    'contacts:delete',
    'interviews:create',
    'interviews:read',
    'interviews:update',
    'interviews:delete',
    'notes:create',
    'notes:read',
    'notes:update',
    'notes:delete',
    'admin:users:list',
    'admin:users:read',
    'admin:users:updateRole',
    'admin:users:delete',
  ]
}
